# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# list of resource config to be applied
resources:
- recall-deployment.yaml
- recall-service.yaml
- virtual-service.yaml

# # namespace to deploy all resources to
# namespace: rs-beta


commonLabels:
  author: cc
