apiVersion: v1
kind: ConfigMap
metadata:
  name: rs-beta-config
data:
  redis_port: "6379"
  redis_host: "REDIS_HOST_PLACEHOLDER"
  messge_broker_redis_port: "6379"
  messge_broker_redis_host: "redis-cart"
  aws_region: "ap-southeast-1"
  s3_bucket: "aws-gcr-rs-sol-demo-ap-southeast-1-522244679887"