apiVersion: v1
kind: Pod
metadata:
  name: pv-pod-1
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['sh', '-c', 'while true; do echo success > /output/output.log; sleep 5; done']
      volumeMounts:
        - name: persistent-storage
          mountPath: /rs-data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-claim